CREATE TABLE item (
  id BIGINT AUTO_INCREMENT NOT NULL,
   id_carrinho BIGINT NOT NULL,
   id_produto BIGINT NULL,
   quantidade INT NOT NULL,
   CONSTRAINT pk_item PRIMARY KEY (id)
);

ALTER TABLE item ADD CONSTRAINT FK_ITEM_ON_ID_CARRINHO FOREIGN KEY (id_carrinho) REFERENCES carrinho (id);

ALTER TABLE item ADD CONSTRAINT FK_ITEM_ON_ID_PRODUTO FOREIGN KEY (id_produto) REFERENCES produto (id);